### ISSUE TITLE
There are inconsistencies between docstring `array_like` and typing `npt.NDArray`

### ISSUE THREAD

**Issue by paddyroddy** [glass-dev/glass#340]
### What is the Topic of Your Question

Other

### Add Your Question Below

It's hard to know what to believe. May not sound like much, but it causes all kinds of problems for #280.

**Comment by ntessore** [comment]
The doctoring `array_like` doesn't have a fixed meaning, at least in how I have always used it. For example, `npt.ArrayLike` allows things like strings, which is why I have moved almost everything to `npt.NDArray[Any]` in newer code.

For static type checking, we probably want `NDArray[Any]` in all cases, if not a more specific typed NDArray.

**Comment by paddyroddy** [comment]
Okay, thanks. That's what I've done in #308, as it caused fewer errors than the alternative.
