### ISSUE TITLE
Code coverage

### ISSUE THREAD

**Issue by ntessore** [glass-dev/glass#46]
Set up codecov or similar to track coverage of unit tests. This should give us a good push to start adding tests, now that we can have them!

**Comment by ntessore** [comment]
This would be nice, and is easy to do, but marking it "future" because it's also not essential for now.

**Comment by Saransh-cpp** [comment]
Hi, @ntessore! Do you have any strong preference for which coverage application to use? I was thinking Codecov because I really like its UI. IIRC, you'll need to add an API token (CODECOV_TOKEN) in the repository secrets on GitHub and enable a few settings (PR comments, annotations, badge) in Codecov to get everything working. I'll create a PR updating the workflow and config files.

**Comment by ntessore** [comment]
No preference for codecov or coveralls from my side, so I am happy to enable codecov right now for this repository.

**Comment by paddyroddy** [comment]
I have a mild preference for `coveralls` (I find `codecov` can be a bit noisy and false-positivey). However, we as a group, recommend both http://github-pages.arc.ucl.ac.uk/python-tooling/pages/ci.html#coverage-monitoring

**Comment by Saransh-cpp** [comment]
I'll go with coveralls, haven't used it before so would be a good learning opportunity

**Comment by Saransh-cpp** [comment]
Sent a coveralls request to organisation owners for approval ✅
